### ISSUE TITLE
registered_at should be filled on server side on report submission

### ISSUE THREAD

**Issue by mjurkus** [vilnius/tvarkau-vilniu-ms#109]
When submitting new report `registered_at` should be filled on backend instead of client.

**Comment by mjurkus** [comment]
@laurynas

**Comment by mjurkus** [comment]
and I think it makes sense to make it mandatory

**Comment by laurynas** [comment]
Maybe in this case it is worth dropping `registered_at`, because it is duplicating `created_at`? 
`created_at` is always populated on report creation. We could return it to the clients too.

**Comment by mjurkus** [comment]
Yeah, sounds reasonable.
