### ISSUE TITLE
Add lat/lng report filtering support

### ISSUE THREAD

**Issue by mjurkus** [vilnius/tvarkau-vilniu-ms#113]
Allow to filter by `lat` and `lng`.

I guess it should accept `lat_from` `lat_to` `lng_from` `lng_to`? Or is there a better way? 
And return matching results in a given box.

@laurynas

**Comment by laurynas** [comment]
Yes, from/to coordinates would be most straightforward. Another option would be to use [geokit-rails](https://github.com/geokit/geokit-rails) gem which would searching by center coords and radius. 

Which way would you prefer?

**Comment by mjurkus** [comment]
Let's choose straightforward approach.

**Comment by laurynas** [comment]
Deployed.
