### ISSUE TITLE
Separate /users and /token resources

### ISSUE THREAD

**Issue by tadaskay** [vilnius/tvarkau-vilniu-ms#4]
As `GET` should be idempotent (currently it's not as `GET /user/token` alters server state), I suggest separating tokens from users.
Current registration flow looks like this:
1. `GET /user/token` - creates a user giving back the token 
Suggested flow:
1. `GET /token` - generates a unique token
2. `POST /users <json body with token>` - create a user for the provided token

**Comment by eimantas** [comment]
Is the step 2 going to check for the validity of the token? I think it should. O therwise it leaves the space for the client to generate the token.

**Comment by tadaskay** [comment]
Yes, it should validate and check if there's no other user registered under given token.
