### ISSUE TITLE
Add report types & report statuses seeds

### ISSUE THREAD

**Issue by laurynas** [vilnius/tvarkau-vilniu-ms#86]

**Comment by laurynas** [comment]
@mjurkus it would be good to get all possible report types and statuses - I would create a seed and populate the database.

**Comment by mjurkus** [comment]
Report statuses:
- Registruota
- Nagrinėjama
- Išnagrinėta

In older version we had other statuses - delayed and forwarded. Now I see only these.

**Comment by mjurkus** [comment]
Report types:

- Aplinkos tvarkymas
- Beglobių gyvūnų gaudymas
- Duobės, įgriuvos, šuliniai
- Dviračių takai
- Eismo organizavimas
- Energetika ir inžineriniai tinklai
- Gatvių apšvietimas
- Gatvių priežiūra
- Gyvūnų laikymas
- Reklamos pažeidimai
- Kapinių priežiūra
- Kiemų dangos remontas
- Komunalinės atliekos
- Laiptai
- Pastatų administravimas
- Šaligatvių remontas
- Statinių priežiūra
- Susisiekimo statiniai
- Transporto stovėjimo  pažeidimai (only for registered members see https://github.com/vilnius/tvarkau-vilniu-ms/issues/100)
- Triukšmo taisyklių pažeidimas
- Tvarkymo ir švaros taisyklių pažeidimas
- Žaidimo ir sporto aikštelės
- Viešasis transportas
- Želdynų priežiūra
- Žvyrkeliai

**Comment by laurynas** [comment]
Great, thanks! Would it be possible get `avilys_status` codes for "Nagrinėjama" and "Išnagrinėta"? 
I already have set `registered` for "Registruota".

**Comment by mjurkus** [comment]
Will do

**Comment by mjurkus** [comment]
![image](https://user-images.githubusercontent.com/427661/46851895-c4fcef80-ce01-11e8-9a28-81880dda6a44.png)

@laurynas

**Comment by laurynas** [comment]
Thanks!

**Comment by laurynas** [comment]
Deployed to production.
